# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# User.create(username: "admin_api", email: "admin@domain.com", password: "admin123",password_confirmation: "admin123", role: 0)
# User.create(username: "Jesus Oliveros", email: "olijeso@yahoo.com.mx", password: "olijeso", password_confirmation: "olijeso", role: 0)
# User.create(username: "Pedro Aguilar", email: "aguilar285@hotmail.com", password: "aguilar285", password_confirmation: "aguilar285", role: 1)
# User.create(username: "Raul Padilla Campos", email: "raulpcampos@yahoo.com.mx", password: "raulpcampos", password_confirmation: "raulpcampos", role: 1)
# User.create(username: "Jose Luis Hernandez", email: "luishp1@gmail.com", password: "luishp1", password_confirmation: "luishp1", role: 1)
# User.create(username: "Francisco Garcia", email: "org3_fgz@yahoo.com.mx", password: "org3_fgz", password_confirmation: "org3_fgz", role: 1)
# User.create(username: "Luis Gerardo", email: "ochoabayonalg@yahoo.com.mx", password: "ochoabayonalg", password_confirmation: "ochoabayonalg", role: 1)
# User.create(username: "Jorge Mora", email: "moradelatorre@gmail.com", password: "moradelatorre", password_confirmation: "moradelatorre", role: 1)
# User.create(username: "Ricardo", email: "riverdet@yahoo.com.mx", password: "riverdet", password_confirmation: "riverdet", role: 1)

# State.create(name: "Aguascalientes") 
# State.create(name: "Baja California,") 
# State.create(name: "Baja California Sur") 
# State.create(name: "Campeche") 
# State.create(name: "Chihuahua") 
# State.create(name: "Chiapas") 
# State.create(name: "Coahuila") 
# State.create(name: "Colima") 
# State.create(name: "Durango") 
# State.create(name: "Guanajuato") 
# State.create(name: "Guerrero") 
# State.create(name: "Hidalgo") 
# State.create(name: "Jalisco") 
# State.create(name: "México") 
# State.create(name: "Michoacán") 
# State.create(name: "Morelos") 
# State.create(name: "Nayarit") 
# State.create(name: "Nuevo León") 
# State.create(name: "Oaxaca") 
# State.create(name: "Puebla") 
# State.create(name: "Querétaro") 
# State.create(name: "Quintana Roo") 
# State.create(name: "San Luis Potosí") 
# State.create(name: "Sinaloa") 
# State.create(name: "Sonora") 
# State.create(name: "Tabasco") 
# State.create(name: "Tamaulipas") 
# State.create(name: "Tlaxcala") 
# State.create(name: "Veracruz") 
# State.create(name: "Yucatán") 
# State.create(name: "Zacatecas") 


# City.create(name: "Aguascalientes", state_id: 1)
# City.create(name: "Mexicali", state_id: 2)
# City.create(name: "La Paz", state_id: 3)
# City.create(name: "San Francisco de Campeche", state_id: 4)
# City.create(name: "Chihuahua", state_id: 5)
# City.create(name: "Tuxtla Gutiérrez", state_id: 6)
# City.create(name: "Saltillo", state_id: 7)
# City.create(name: "Colima", state_id: 8)
# City.create(name: "Victoria de Durango", state_id: 9)
# City.create(name: "Guanajuato", state_id: 10)
# City.create(name: "Chilpancingo de los Bravo", state_id: 11)
# City.create(name: "Pachuca de Soto", state_id: 12)
# City.create(name: "Guadalajara", state_id: 13)
# City.create(name: "Toluca de Lerdo", state_id: 14)
# City.create(name: "Morelia", state_id: 15)
# City.create(name: "Cuernavaca", state_id: 16)
# City.create(name: "Tepic", state_id: 17)
# City.create(name: "Monterrey", state_id: 18)
# City.create(name: "Oaxaca de Juárez", state_id: 19)
# City.create(name: "Puebla de Zaragoza", state_id: 20)
# City.create(name: "Santiago de Querétaro", state_id: 21)
# City.create(name: "Chetumal", state_id: 22)
# City.create(name: "San Luis Potosí", state_id: 23)
# City.create(name: "Culiacán Rosales", state_id: 24)
# City.create(name: "Hermosillo", state_id: 25)
# City.create(name: "Villahermosa", state_id: 26)
# City.create(name: "Ciudad Victoria", state_id: 27)
# City.create(name: "Tlaxcala de Xicohténcatl", state_id: 28)
# City.create(name: "Xalapa-Enríquez", state_id: 29)
# City.create(name: "Mérida", state_id: 30)
# City.create(name: "Zacatecas", state_id: 31)
# City.create(name: "Acapulco", state_id: 11)

# Shop.create(plaza: "TAMAZUNCHALE", shop_number: 51, name: "TAMAZUNZAPA", address: "AV.HIDALGO #504", suburb: "CENTRO", location: "TAMAZUNCHALE", state_id: 23, cp: 79960)

Area.create(name: "Caballeros")
Area.create(name: "Damas")
Area.create(name: "Deportes")
Area.create(name: "Niños")
Area.create(name: "Saldos")

