# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# User.create(username: "admin_api", email: "admin@domain.com", password: "admin123",password_confirmation: "admin123", role: 0)
# User.create(username: "Jesus Oliveros", email: "olijeso@yahoo.com.mx", password: "olijeso", password_confirmation: "olijeso", role: 0)
# User.create(username: "Pedro Aguilar", email: "aguilar285@hotmail.com", password: "aguilar285", password_confirmation: "aguilar285", role: 1)
# User.create(username: "Raul Padilla Campos", email: "raulpcampos@yahoo.com.mx", password: "raulpcampos", password_confirmation: "raulpcampos", role: 1)
# User.create(username: "Jose Luis Hernandez", email: "luishp1@gmail.com", password: "luishp1", password_confirmation: "luishp1", role: 1)
# User.create(username: "Francisco Garcia", email: "org3_fgz@yahoo.com.mx", password: "org3_fgz", password_confirmation: "org3_fgz", role: 1)
# User.create(username: "Luis Gerardo", email: "ochoabayonalg@yahoo.com.mx", password: "ochoabayonalg", password_confirmation: "ochoabayonalg", role: 1)
# User.create(username: "Jorge Mora", email: "moradelatorre@gmail.com", password: "moradelatorre", password_confirmation: "moradelatorre", role: 1)
# User.create(username: "Ricardo", email: "riverdet@yahoo.com.mx", password: "riverdet", password_confirmation: "riverdet", role: 1)

# State.create(name: "Aguascalientes") 1
# State.create(name: "Baja California,") 2
# State.create(name: "Baja California Sur") 3 
# State.create(name: "Campeche") 4
# State.create(name: "Chihuahua") 5
# State.create(name: "Chiapas") 6
# State.create(name: "Coahuila") 7
# State.create(name: "Colima") 8
# State.create(name: "Durango") 9
# State.create(name: "Guanajuato") 10
# State.create(name: "Guerrero") 11
# State.create(name: "Hidalgo") 12
# State.create(name: "Jalisco") 13
# State.create(name: "México") 14
# State.create(name: "Michoacán") 15
# State.create(name: "Morelos") 16
# State.create(name: "Nayarit") 17
# State.create(name: "Nuevo León") 18 
# State.create(name: "Oaxaca") 19
# State.create(name: "Puebla") 20
# State.create(name: "Querétaro") 21 
# State.create(name: "Quintana Roo") 22
# State.create(name: "San Luis Potosí") 23
# State.create(name: "Sinaloa") 24
# State.create(name: "Sonora") 25
# State.create(name: "Tabasco") 26
# State.create(name: "Tamaulipas") 27 
# State.create(name: "Tlaxcala") 28
# State.create(name: "Veracruz") 29
# State.create(name: "Yucatán") 30
# State.create(name: "Zacatecas") 31

# Shop.create(plaza:"DURANGO" , shop_number:331 , name:"ZAP. DUMAR" , address:"FCO. I. MADERO 401 SUR" , suburb:"CENTRO" , location:"DURANGO, DGO." , state_id: 9, cp:34000 ) 
# Shop.create(plaza:"DURANGO" , shop_number:332 , name:"DURFEZA" , address:"AV. 20 DE NOV. 200 PTE" , suburb:"CENTRO" , location:"DURANGO, DGO." , state_id: 9, cp:34000 ) 
# Shop.create(plaza:"DURANGO" , shop_number:333 , name:"ZAPADU" , address:"5 DE FEB 313 PTE" , suburb:"CENTRO" , location:"DURANGO, DGO." , state_id: 9, cp:3400 ) 
# Shop.create(plaza:"CABORCA" , shop_number:464 , name:"ZAPACABORCA" , address:"AV 6 DE ABRIL #2" , suburb:"CENTRO" , location:"H CABORCA" , state_id: 25, cp:83600 ) 
# Shop.create(plaza:"OCOTLAN" , shop_number:401 , name:"ZACOTLAN SADE CV" , address:"RAMON CORONA # 365" , suburb:"CENTRO" , location:"OCOTLAN" , state_id: 28, cp:47800 ) 
# Shop.create(plaza:"TEPATITLAN" , shop_number:399 , name:"TEPAZAPA S.A. DE C.V." , address:"PROGRESO #50" , suburb:"CENTRO" , location:"TEPATITLAN" , state_id: 13, cp:47600 ) 
# Shop.create(plaza:"TECOMAN" , shop_number:405 , name:"TECOMANZAPA" , address:"18 DE JULIO #349" , suburb:"CENTRO" , location:"TECOMAN" , state_id: 8, cp:28100 ) 
# Shop.create(plaza:"CABORCA" , shop_number:464 , name:"ZAPACABORCA" , address:"AV 6 DE ABRIL #2" , suburb:"CENTRO" , location:"H CABORCA" , state_id: 25, cp:83600 ) 
# Shop.create(plaza:"ENSENADA" , shop_number:492 , name:"CALZADO JUMIR" , address:"JUAREZ Y MIRAMAR ·703" , suburb:"CENTRO" , location:"ENSENADA" , state_id: 2, cp:22800 ) 
# Shop.create(plaza:"ENSENADA" , shop_number:493 , name:"ZAPATERA ENBACA" , address:"JUAREZ Y RIVEROL" , suburb:"CENTRO" , location:"ENSENADA" , state_id: 2, cp:22800 ) 
# Shop.create(plaza:"ENSENADA" , shop_number:494 , name:"ENSEMIRAZA" , address:"JUAREZ Y MIRARAR 675 INT-6" , suburb:"CENTRO" , location:"ENSENADA" , state_id: 2, cp:22800 ) 
# Shop.create(plaza:"PEÑASCO" , shop_number:463 , name:"zapeñasco" , address:"juan de la barrera #151" , suburb:"CENTRO" , location:"pto peñasco" , state_id: 25, cp:83550 ) 
# Shop.create(plaza:"TEPIC" , shop_number:387 , name:"ZAPATERIA ZATE" , address:"AMADO NERVO 37 PTE." , suburb:"CENTRO" , location:"TEPIC" , state_id: 17, cp:63000 ) 
# Shop.create(plaza:"TEPIC" , shop_number:388 , name:"TEPIZA" , address:"VERACRUZ 185 NTE." , suburb:"CENTRO" , location:"TEPIC" , state_id: 17, cp:63000 ) 
# Shop.create(plaza:"TEPIC" , shop_number:389 , name:"ZATENAYA" , address:"AV. MEXICO 265" , suburb:"CENTRO" , location:"TEPIC" , state_id: 17, cp:63000 ) 
# Shop.create(plaza:"TEPIC" , shop_number:390 , name:"TEPISOR" , address:"AV. DE LOS INSURGENTES 368 LOCALES. 11-12-13" , suburb:"LOS LLANITOS" , location:"TEPIC" , state_id: 17, cp:63170 ) 
# Shop.create(plaza:"SAN LUIS R.C" , shop_number:472 , name:"ZAPATERAPENTEL" , address:"ALVARO OBREGON #111" , suburb:"CUAUHTEMOC" , location:"SAN LUIS RIO COL" , state_id: , cp:83400 ) 
# Shop.create(plaza:"MEXICALI" , shop_number:465 , name:"MEXIGALEZA" , address:"BLVD.LAZARO CARDENAS #2200 LOCAL 66,67." , suburb:"EL PORVENIR" , location:"MEXICALI" , state_id: 2, cp:21190 ) 
# Shop.create(plaza:"MEXICALI" , shop_number:466 , name:"ZAMCALI" , address:"BLVD. LOPEZ MATEOS #440 PRIMERA SECCION " , suburb:"CENTRO " , location:"MEXICALI" , state_id: 2, cp:21100 ) 
# Shop.create(plaza:"MEXICALI" , shop_number:469 , name:"ZAPATERA CACHAMEXI" , address:"BLVD. LOPEZ MATEOS Y LERDO LOCAL 29-34 ZONA K PLAZA CACHANILLA" , suburb:"JABONERA" , location:"MEXICALI" , state_id: 2, cp:21100 ) 
# Shop.create(plaza:"MEXICALI" , shop_number:470 , name:"ZAPAMEXICALI" , address:"BLVD. LAZARO CARDENAS #2955 LOCAL 86" , suburb:"GONZALES ORTEGA" , location:"MEXICALI" , state_id: 2, cp:21396 ) 
# Shop.create(plaza:"DELICIAS" , shop_number:353 , name:"Delchiza SA de CV" , address:"Tercera Norte # 2" , suburb:"Centro" , location:"Delicias" , state_id: , cp:33000 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:474 , name:"MACROTIZA S.A. DE C.V." , address:"AV.INSURGENTES ESQ. PASEO DEL PARQUE S/N L7 Y L8" , suburb:"RIO TIJUANA 3RA. ETAPA" , location:"TIJUANA" , state_id: 2, cp:22226 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:475 , name:"TIDIEZAPA S.A. DE C.V" , address:"BLVD. DIAZ ORDAZ # 14517 L 1 AL 6 Y 17" , suburb:"LAS FUENTES" , location:"TIJUANA" , state_id: 2, cp:22117 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:476 , name:"TIBUZAPA S.A. DE C.V." , address:"AV.EJIDO MATAMOROS # 21907-001" , suburb:"GRANJAS FAMILIARES DEL MATAMOROS" , location:"TIJUANA" , state_id: 2, cp:22203 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:477 , name:"ZAPATERIA BAJANORTE S.A. DE C.V." , address:"CALLE 2DA. BENITO JUAREZ # 7880" , suburb:"CENTRO" , location:"TIJUANA" , state_id: 2, cp:22000 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:480 , name:"CALZADO ROLEIND S.A. DE C.V." , address:"3RA. CARRILLO PUERTO # 8116" , suburb:"CENTRO" , location:"TIJUANA" , state_id: 2, cp:22000 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:481 , name:"ZADOSBE S.A. DE C.V." , address:"2DA. BENITO JUAREZ # 8084" , suburb:"CENTRO" , location:"TIJUANA" , state_id: 2, cp:22000 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:482 , name:"ZAPATERIA NIHETI S.A. DE C.V." , address:"AV.NIÑOS HEROES # 860" , suburb:"CENTRO" , location:"TIJUANA" , state_id: 2, cp:22000 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:483 , name:"ZAPATERIAS BATORCE S.A. DE C.V." , address:"AV. NIÑOS HEROES # 975" , suburb:"CENTRO" , location:"TIJUANA" , state_id: 2, cp:22000 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:484 , name:"ZAPATERIA MESTIBA S.A. DE C.V." , address:"BLVD. DIAZ ORDAZ #170" , suburb:"LA MESA" , location:"TIJUANA" , state_id: 2, cp:22105 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:485 , name:"ZATIJUR S.A. DE C.V." , address:"2DA.BENITO JUAREZ Y AV. REVOLUCION # 792" , suburb:"CENTRO" , location:"TIJUANA" , state_id: 2, cp:22000 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:486 , name:"TIJUAZAPA S.A. DE C.V." , address:"BLVD. DIAZ ORDAZ # 3725" , suburb:"CASTRO GREEN" , location:"TIJUANA" , state_id: 2, cp:22127 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:487 , name:"TIRIOZA S.A. DE C.V." , address:"AV. PASEO DE LOS HEROES # 9550 LOCAL B 18" , suburb:"ZONA URBANA RIO TIJUANA" , location:"TIJUANA" , state_id: 2, cp:22320 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:488 , name:"OTAY ZAPATERA S.A. DE C.V" , address:"CALZ. LAZARO CARDENAS # 1900 LOCALES D6 D7 D8" , suburb:"NUEVA TIJUANA" , location:"TIJUANA" , state_id: 2, cp:22435 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:489 , name:"MESATIZA S.A. DE C.V." , address:"BLVD.DIAZ ORDAZ # 1269" , suburb:"LAS HUERTAS 1RA. SECCION" , location:"TIJUANA" , state_id: 2, cp:22116 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:490 , name:"ZAPATIJUA S.A. DE C.V." , address:"RUTA MATAMOROS # 7801" , suburb:"MARIANO MATAMOROS NORTE" , location:"TIJUANA" , state_id: 2, cp:22206 ) 
# Shop.create(plaza:"TIJUANA" , shop_number:491 , name:"SENDETIJUA S.A. DE C.V." , address:"CARRETERA LIBRE TIJUANA-MEXICALI # 25420" , suburb:"FIDEICOMISO EL FLORIDO" , location:"TIJUANA" , state_id: 2, cp:22245 ) 
# Shop.create(plaza:"TECATE" , shop_number:496 , name:"ZAPATECATE S.A DE C.V" , address:"PRESIDENTE ELIAS CALLES NUM 490" , suburb:"CENTRO" , location:"TECATE" , state_id: , cp:21400 ) 
# Shop.create(plaza:"COLIMA" , shop_number:396 , name:"ZAPACOL S.A DE C.V" , address:"FCO.I MADERO 72" , suburb:"CENTRO" , location:"COLIMA" , state_id: 8, cp:28000 ) 
# Shop.create(plaza:"GUADALAJARA" , shop_number:376 , name:"HIDALGO ZAPATERA S.A DE C.V" , address:"Hidalgo Num 550" , suburb:"Centro" , location:"Guadalajara" , state_id: 13, cp:44100 ) 
# Shop.create(plaza:"GUADALAJARA" , shop_number:377 , name:"ZAPATERA PEMOC S.A DE C.V" , address:"Ocampo Num 33" , suburb:"Centro" , location:"Guadalajara" , state_id: 13, cp:44100 ) 
# Shop.create(plaza:"GUADALAJARA" , shop_number:379 , name:"GALEANA ZAPATERA S.A DE C.V" , address:"Galeana Num 21" , suburb:"Centro" , location:"Guadalajara" , state_id: 13, cp:44100 ) 
# Shop.create(plaza:"GUADALAJARA" , shop_number:381 , name:"ZAGUASOL S.A DE C.V" , address:"Av. Lopez Mateos Zona Z Local D-19" , suburb:"Ciudad del sol" , location:"Zapopan" , state_id: 13, cp:45055 ) 
# Shop.create(plaza:"GUADALAJARA" , shop_number:382 , name:"ZACASON S.A DE C.V" , address:"Juarez Num 445" , suburb:"Centro" , location:"Guadalajara" , state_id:13 , cp:44100 ) 
# Shop.create(plaza:"GUADALAJARA" , shop_number:383 , name:"CASONA ZAPATERA S.A DE C.V" , address:"Hidaldo Num 431" , suburb:"Centro" , location:"Guadalajara" , state_id: 13, cp:44100 ) 
# Shop.create(plaza:"GUADALAJARA" , shop_number:384 , name:"PLATAZAGUA S.A DE C.V" , address:"Morelos Num 66" , suburb:"Centro" , location:"Guadalajara" , state_id: 13, cp:44100 ) 
# Shop.create(plaza:"GUADALAJARA" , shop_number:385 , name:"ZAGUACABA S.A DE C.V" , address:"Javier Mina Num 202" , suburb:"San Juan De Dios" , location:"Guadalajara." 13, state_id: , cp:44360 ) 
# Shop.create(plaza:"GUADALAJARA" , shop_number:386 , name:"CENTROSUZA S.A DE C.V " , address:"Colon Num 163" , suburb:"Centro" , location:"Guadalajara" , state_id: 13, cp:44100 ) 
# Shop.create(plaza:"MANZANILLO" , shop_number:403 , name:"MACOLIZA S.A DE C.V" , address:"AV. MEXICO #250" , suburb:"CENTRO" , location:"MANZANILLO" , state_id: 8, cp:28200 ) 
# Shop.create(plaza:"TORREON" , shop_number:325 , name:"Zatocua S.A. de C.V." , address:"Av. Hidalgo # 1259 Pte." , suburb:"Centro" , location:"Torreon" , state_id: 7, cp:27000 ) 
# Shop.create(plaza:"TORREON" , shop_number:327 , name:"Hidatoza S.A. de C.V" , address:"Av. Hidalgo # 1547 Pte." , suburb:"Centro" , location:"Torreon" , state_id: 7, cp:27000 ) 
# Shop.create(plaza:"TORREON" , shop_number:328 , name:"Zaapatorco S.A. de C.V." , address:"Av. Hidalgo # 1415 Pte." , suburb:"Centro" , location:"Torreon" , state_id: 7, cp:27000 ) 
# Shop.create(plaza:"TORREON" , shop_number:329 , name:"Torreonzapa S.A de C.V." , address:"Av. Hidalgo # 999 Pte." , suburb:"Centro" , location:"Torreon" , state_id: 7, cp:27000 ) 
# Shop.create(plaza:"GOMEZ PALACIO" , shop_number:338 , name:"Gomezapa S.A. de C.V." , address:"Av.Victoria # 378 Sur" , suburb:"Centro" , location:"Gomez Palacio" , state_id: , cp:35000 ) 
# Shop.create(plaza:"CD GUZMAN" , shop_number:406 , name:"Guzmanzapa SA de CV" , address:"Reforma 32" , suburb:"Centro" , location:"CD. Guzman" , state_id: , cp:49000 ) 
# Shop.create(plaza:"CD CUAUHTEMOC " , shop_number:355 , name:"ZAPACUACHI S.A DE C.V" , address:"HIDALGO #318" , suburb:"CENTRO" , location:"CD CUAUHTEMOC" , state_id: , cp:31500 ) 
# Shop.create(plaza:"PARRAL" , shop_number:351 , name:"zaparral" , address:"calle maclovio Herrera #20" , suburb:"centro" , location:"Parral" , state_id: , cp:33800 ) 
# Shop.create(plaza:"PARRAL" , shop_number:352 , name:"parralzapa" , address:"calle colegio #8y10" , suburb:"centro" , location:"Parral" , state_id: , cp:33800 ) 
# Shop.create(plaza:"CHIHUAHUA" , shop_number:343 , name:"CALZADO DROMEJA S.A. DE C.V." , address:"LIBERTAD No. 300" , suburb:"CENTRO" , location:"CHIHUAHUA" , state_id: 5, cp:31000 ) 
# Shop.create(plaza:"CHIHUAHUA" , shop_number:345 , name:"ZAPATERIA ZACHI S.A. DE C.V." , address:"LIBERTAD No. 211" , suburb:"CENTRO" , location:"CHIHUAHUA" , state_id: 5, cp:31000 ) 
# Shop.create(plaza:"CHIHUAHUA" , shop_number:347 , name:"ZAPACHIMER S.A. DE C.V." , address:"LIBERTAD No. 601" , suburb:"CENTRO" , location:"CHIHUAHUA" , state_id: 5, cp:31000 ) 
# Shop.create(plaza:"CHIHUAHUA" , shop_number:348 , name:"ZALIBERCHI S.A. DE C.V." , address:"LIBERTAD No. 501" , suburb:"CENTRO" , location:"CHIHUAHUA" , state_id: 5, cp:31000 ) 
# Shop.create(plaza:"CHIHUAHUA" , shop_number:349 , name:"SANDECHIZA S.A. DE C.V." , address:"AV. ALEJANDRO DUMAS No. 11377" , suburb:"COMPLEJO IND." , location:"CHIHUAHUA" , state_id: 5, cp:31136 ) 
# Shop.create(plaza:"PUERTO VALLARTA" , shop_number:392 , name:"ZAVALLARTA S.A DE C.V" , address:"EMILIANO ZAPATA #217" , suburb:"CENTRO" , location:"EL PITILLAL" , state_id: , cp:48290 ) 
# Shop.create(plaza:"PUERTO VALLARTA" , shop_number:393 , name:"ZAPAVALLAR S-A DE C.V" , address:"MORELOS #236" , suburb:"CENTRO" , location:"PUERTO VALLARTA" , state_id: , cp:48300 ) 
# Shop.create(plaza:"PUERTO VALLARTA" , shop_number:394 , name:"VALLARTAZAPA S.A DE C.V" , address:"JUAREZ #411" , suburb:"CENTRO" , location:"PUERTO VALLARTA" , state_id: , cp:48300 ) 
# Shop.create(plaza:"PUERTO VALLARTA" , shop_number:395 , name:"NUEVALLAZA S.A DE C.V" , address:"RIVERA NAYARIT #430 INT. C24" , suburb:"VALLE DORADO" , location:"BAHIA DE BANDERAS" , state_id: , cp:63735 ) 
# Shop.create(plaza:"CD. JUAREZ" , shop_number:359 , name:"JUARESOR S.A. DE C.V." , address:"FRANCISCO VILLARREAL TORRES 2050 A L6 y 7D" , suburb:"PARTIDO SENECU" , location:"CD. JUAREZ" , state_id: , cp:32546 ) 
# Shop.create(plaza:"CD. JUAREZ" , shop_number:362 , name:"ZAJUAVELAR S.A. DE C.V" , address:"RAFAEL VELARDE 293" , suburb:"CENTRO" , location:"CD. JUAREZ" , state_id: , cp:32000 ) 
# Shop.create(plaza:"CD. JUAREZ" , shop_number:363 , name:"ZAPATERIA GUEVAR S.A. DE C.V." , address:"VICENTE GUERRERO 400" , suburb:"CENTRO" , location:"CD. JUAREZ" , state_id: , cp:32000 ) 
# Shop.create(plaza:"CD. JUAREZ" , shop_number:364 , name:"JUAJUAZA S.A. DE C.V" , address:"AV. JUAREZ 106" , suburb:"CENTRO" , location:"CD. JUAREZ" , state_id: , cp:32000 ) 
# Shop.create(plaza:"CD. JUAREZ" , shop_number:365 , name:"JUAGUERZA S.A. DE C.V." , address:"VICENTE GUERRERO 282" , suburb:"CENTRO" , location:"CD. JUAREZ" , state_id: , cp:32000 ) 
# Shop.create(plaza:"CD. JUAREZ" , shop_number:366 , name:"CIJUAVELZA S.A. DE C.V" , address:"RAFAEL VELARDE 227" , suburb:"CENTRO" , location:"CD. JUAREZ" , state_id: , cp:32000 ) 
# Shop.create(plaza:"CD. JUAREZ" , shop_number:368 , name:"ZAPAJUFU S.A. DE C.V." , address:"TECNOLOGICO 1770 4" , suburb:"FUENTES DEL VALLE" , location:"CD. JUAREZ" , state_id: , cp:32500 ) 
# Shop.create(plaza:"CD. JUAREZ" , shop_number:369 , name:"ZAJUASORIA S.A DE C.V" , address:"TECNOLOGICO 2701 6 A y B" , suburb:"DEL MARQUEZ" , location:"CD. JUAREZ" , state_id: , cp:32607 ) 
# Shop.create(plaza:"CD. JUAREZ" , shop_number:370 , name:"MINOCHEZA DE JUAREZ S.A. DE C.V" , address:"NOCHE TRISTE 405" , suburb:"CENTRO" , location:"CD. JUAREZ" , state_id: , cp:32000 ) 
# Shop.create(plaza:"CD. JUAREZ" , shop_number:372 , name:"ZAJUASOR S.A DE C.V." , address:"OSCAR FLORES 6751 6 7 8 9" , suburb:"NUEVO HIPODROMO" , location:"CD. JUAREZ" , state_id: , cp:32685 ) 
# Shop.create(plaza:"CD. JUAREZ" , shop_number:373 , name:"JUAZATORRES S.A. DE C.V" , address:"AV. DE LAS TORRES 2111 23 24 25 C" , suburb:"VALLE DE BRAVO" , location:"CD. JUAREZ" , state_id: , cp:32695 ) 
# Shop.create(plaza:"CD. JUAREZ" , shop_number:374 , name:"PATIOZARAJUAZA S.A DE C.V." , address:"BLVD. ZARAGOZA 6008 C13" , suburb:"PARQUE INDUSTRIAL ZARAGOZA" , location:"CD. JUAREZ" , state_id: , cp:32685 ) 
# Shop.create(plaza:"AGS" , shop_number:34 , name:"GUAPAZA" , address:"5 DE MAYO NO. 230" , suburb:"CENTRO" , location:"AGUASCALIENTES" , state_id: , cp:20000 ) 
# Shop.create(plaza:"AGS" , shop_number:36 , name:"AGUASALLE" , address:"ALLENDE 109-111" , suburb:"CENTRO" , location:"AGUASCALIENTES" , state_id: , cp:20000 ) 
# Shop.create(plaza:"SLP" , shop_number:38 , name:"SANLUISZAPA" , address:"HIDALGO #425" , suburb:"CENTRO" , location:"SLP" , state_id: , cp:78000 ) 
# Shop.create(plaza:"SLP" , shop_number:39 , name:"HIPOTAZA" , address:"HIDALGO #503" , suburb:"CENTRO" , location:"SLP" , state_id: , cp:78000 ) 
# Shop.create(plaza:"SLP" , shop_number:41 , name:"LUISZAPA" , address:"HIDALGO #205-213-215" , suburb:"CENTRO" , location:"SLP" , state_id: , cp:78000 ) 
# Shop.create(plaza:"SLP" , shop_number:42 , name:"SANLUISOR" , address:"AV. BENITO JUAREZ 2005, LOC 8 Y 9, BLOQUE D" , suburb:"ESTRELLA DE ORIENTE" , location:"SLP" , state_id: , cp:78396 ) 
# Shop.create(plaza:"FRESNILLO" , shop_number:43 , name:"ZAFREZA. " , address:" AV. BENITO JUAREZ PTE. # 1" , suburb:"CENTRO" , location:"FRESNILLO" , state_id: , cp:99000 ) 
# Shop.create(plaza:"ZACATECAS" , shop_number:46 , name:"ZAZACA" , address:"HIDALGO 64" , suburb:"46" , location:"ZAC" , state_id: , cp:98000 ) 
# Shop.create(plaza:"RIOVERDE" , shop_number:48 , name:"RIOVERZA" , address:"PABLO VERASTEGUI 121 P.B." , suburb:"CENTRO" , location:"RIOVERDE" , state_id: , cp:79610 ) 
# Shop.create(plaza:"MORELIA" , shop_number:56 , name:"MORALZA" , address:"VASCO DE QUIROGA 185" , suburb:"CENTRO" , location:"MORELIA" , state_id: , cp:58000 ) 
# Shop.create(plaza:"MORELIA" , shop_number:57 , name:"VALLAMORZA" , address:"VALLADOLID 42" , suburb:"CENTRO" , location:"MORELIA" , state_id: , cp:58000 ) 
# Shop.create(plaza:"MORELIA" , shop_number:58 , name:"QUIROGA" , address:"VASCO DE QUIROGA 430" , suburb:"CENTRO" , location:"MORELIA" , state_id: , cp:58000 ) 
# Shop.create(plaza:"URUAPAN" , shop_number:60 , name:"ZAPARUAPAN" , address:"EMILIO CARRANZA#10" , suburb:"CENTRO" , location:"URUAPAN" , state_id: , cp:60000 ) 
# Shop.create(plaza:"URUAPAN" , shop_number:61 , name:"URUAPAN ZAPATERA" , address:"PORTAL MATAMOROS#13" , suburb:"CENTRO" , location:"URUAPAN" , state_id: , cp:60000 ) 
# Shop.create(plaza:"ACÀMBARO" , shop_number:64 , name:"ZAPACAMBA" , address:"CALLE ALDAMA No 2" , suburb:"CENTRO" , location:"ACÀMBARO" , state_id: , cp:38600 ) 
# Shop.create(plaza:"ZAMORA" , shop_number:66 , name:"ZAZA" , address:"GUERRERO 60 OTE" , suburb:"CENTRO" , location:"ZAMORA" , state_id: , cp:59600 ) 
# Shop.create(plaza:"MOROLEON" , shop_number:68 , name:"MOROLEZA" , address:"HIDALGO 64" , suburb:"CENTRO" , location:"MOROLEON" , state_id: , cp:38800 ) 
# Shop.create(plaza:"LA PIEDAD" , shop_number:70 , name:"LAPIEZAP" , address:"Aquiles Serdán 83" , suburb:"CENTRO" , location:"LA PIEDAD" , state_id: , cp:59300 ) 
# Shop.create(plaza:"APATZINGAN" , shop_number:75 , name:"ZAPATZIN" , address:"ESTEBAN VACA CALDERON # 346" , suburb:"CENTRO" , location:"APATZINGAN " , state_id: , cp:60600 ) 
# Shop.create(plaza:"ZACAPU" , shop_number:76 , name:"ZACAPUZA" , address:"AV. MORELOS # 517" , suburb:"CENTRO" , location:"ZACAPU" , state_id: , cp:58600 ) 
# Shop.create(plaza:"ZIHUATANEJO" , shop_number:146 , name:"ZIHUAZAPA" , address:"JUAREZ 31" , suburb:"CENTRO" , location:"ZIHUATANEJO" , state_id: , cp:40880 ) 
# Shop.create(plaza:"LAZARO CAR" , shop_number:148 , name:"ZAPALAZA" , address:"LAZARO CARDENAS 2100" , suburb:"CENTRO" , location:"LAZARO CARDENAS" , state_id: , cp:60950 ) 
# Shop.create(plaza:"LAZARO CAR" , shop_number:149 , name:"LAZAPA" , address:"LAZARO CARDENAS 1683" , suburb:"CENTRO" , location:"LAZARO CARDENAS" , state_id: , cp:60950 ) 
# Shop.create(plaza:"MAZATLAN" , shop_number:408 , name:"SORIAMAZA" , address:"OSCAR PEREZ ESCOBOSA No. 2801 LOCAL 8D" , suburb:"" , location:"MAZATLAN" , state_id: , cp:82127 ) 
# Shop.create(plaza:"MAZATLAN" , shop_number:409 , name:"ZAPATERA BEJULVA" , address:"LEANDRO VALLE No. 31-A PTE" , suburb:"CENTRO" , location:"MAZATLAN" , state_id: , cp:82000 ) 
# Shop.create(plaza:"MAZATLAN" , shop_number:410 , name:"ZAMAZTLA ZAPATERA" , address:"AQUILES SERDAN No. 1628" , suburb:"CENTRO" , location:"MAZATLAN" , state_id: , cp:82000 ) 
# Shop.create(plaza:"MAZATLAN" , shop_number:411 , name:"ZAPAMAZATLA" , address:"LEANDRO VALLE Y AQUILES SERDAN S/N " , suburb:"CENTRO" , location:"MAZATLAN" , state_id: , cp:82000 ) 
# Shop.create(plaza:"MAZATLAN" , shop_number:412 , name:"MERMAZA" , address:"MELCHOR OCAMPO No. 20 PTE" , suburb:"CENTRO" , location:"MAZATLAN" , state_id: , cp:82000 ) 
# Shop.create(plaza:"CULIACAN" , shop_number:413 , name:"SENDECULZA" , address:"JOSE LIMON NORTE 2545 LOCS. D5-D6" , suburb:"HUMAYA" , location:"CULIACAN" , state_id: , cp:80020 ) 
# Shop.create(plaza:"CULIACAN" , shop_number:414 , name:"SINACAN" , address:"DOMINGO RUBI 185 NORTE" , suburb:"CENTRO" , location:"CULIACAN" , state_id: , cp:80000 ) 
# Shop.create(plaza:"CULIACAN" , shop_number:415 , name:"CUSIN" , address:"DOMINGO RUBI 623 NORTE" , suburb:"CENTRO" , location:"CULIACAN" , state_id: , cp:80000 ) 
# Shop.create(plaza:"CULIACAN" , shop_number:416 , name:"RUBICO" , address:"BENITO JUAREZ Y DOMINGO RUBI S/N" , suburb:"CENTRO" , location:"CULIACAN" , state_id: , cp:80000 ) 
# Shop.create(plaza:"CULIACAN" , shop_number:417 , name:"CULIJU" , address:"BENITO JUAREZ 137 PTE" , suburb:"CENTRO" , location:"CULIACAN" , state_id: , cp:80000 ) 
# Shop.create(plaza:"CULIACAN" , shop_number:418 , name:"SORIACUL" , address:"BLVD. E. ZAPATA 2151 PTE L .26 AL 29" , suburb:"VALLADO" , location:"CULIACAN" , state_id: , cp:80110 ) 
# Shop.create(plaza:"CULIACAN" , shop_number:420 , name:"MOSIN" , address:"HIDALGO 215 PTE" , suburb:"CENTRO" , location:"LOS MOCHIS" , state_id: , cp:81200 ) 
# Shop.create(plaza:"CULIACAN" , shop_number:421 , name:"SINMOCHIZ" , address:"A.OBREGON 439 PTE" , suburb:"CENTRO" , location:"LOS MOCHIS" , state_id: , cp:81200 ) 
# Shop.create(plaza:"MOCHIS" , shop_number:422 , name:"ZAMOCHI" , address:"A.OBREGON 223 PTE" , suburb:"CENTRO" , location:"LOS MOCHIS" , state_id: , cp:81200 ) 
# Shop.create(plaza:"MOCHIS" , shop_number:423 , name:"ZAPAMOCHIS" , address:"IND Y ZARAGOZA 317 SUR L-E" , suburb:"CENTRO" , location:"LOS MOCHIS" , state_id: , cp:81200 ) 
# Shop.create(plaza:"MOCHIS" , shop_number:424 , name:"SENDEMOCHIS" , address:"B.ANTONIO ROSALES 2300 NTE" , suburb:"MIGUEL" , location:"LOS MOCHIS" , state_id: , cp:81210 ) 
# Shop.create(plaza:"LA PAZ" , shop_number:425 , name:"SEPAZA" , address:"16 DE SEPTIEMBRE 114" , suburb:"CENTRO" , location:"LA PAZ" , state_id: , cp:23000 ) 
# Shop.create(plaza:"LA PAZ" , shop_number:426 , name:"LAPAZAPA" , address:"REVOLUCION DE 1910 # 1695" , suburb:"CENTRO" , location:"LA PAZ " , state_id: , cp:23000 ) 
# Shop.create(plaza:"LA PAZ" , shop_number:427 , name:"ZAPALAPAZ" , address:"OCAMPO 315" , suburb:"CENTRO" , location:"LA PAZ" , state_id: , cp:23000 ) 
# Shop.create(plaza:"GUAMUCHIL" , shop_number:429 , name:"GUAMUSIN" , address:"MARIANO ESCOBEDO S/N" , suburb:"CENTRO" , location:"GUAMUCHIL" , state_id: , cp:81400 ) 
# Shop.create(plaza:"GUASAVE" , shop_number:431 , name:"GUASINZA" , address:"ZARAGOZA #734" , suburb:"CENTRO" , location:"GUASAVE" , state_id: , cp:81000 ) 
# Shop.create(plaza:"GUASAVE" , shop_number:432 , name:"GUAZAVEZA" , address:"ZARAGOZA#601" , suburb:"CENTRO" , location:"GUASAVE" , state_id: , cp:81000 ) 
# Shop.create(plaza:"CD.CONSTITUCION" , shop_number:433 , name:"CONSTITUZAPA" , address:"NICOLAS BRAVO S/N" , suburb:"CENTRO" , location:"C.D CONSTITUCION COMUNDU" , state_id: , cp:23600 ) 
# Shop.create(plaza:"CABO SAN LUCAS" , shop_number:434 , name:"ZAPACABO" , address:"jose maria morelos mz 23 lote 01" , suburb:"idelfondo green" , location:"cabo san lucas bcs" , state_id: , cp:23470 ) 
# Shop.create(plaza:"CABO SAN LUCAS" , shop_number:435 , name:"ZAPACABO" , address:"av de las brisas 2404 local 16c" , suburb:"brisas del pacifico" , location:"cabo san lucas bcs" , state_id: , cp:23473 ) 
# Shop.create(plaza:"B.C.S." , shop_number:436 , name:"ZAPAJOSE" , address:"MANUEL DOBLADO S/N MZA 50 LOTE 1 ENTRE CALLE COLEGIO MILITAR Y CALLEJON IBARRA" , suburb:"CENTRO" , location:"SN.JOSE DEL CABO" , state_id: , cp:23400 ) 
# Shop.create(plaza:"MATAMOROS" , shop_number:283 , name:"MATASOR" , address:"AV. CONSTITUYENTES # 300 INT 21 Y 22C" , suburb:"FRACC QUINTA REAL" , location:"MATAMOROS" , state_id: , cp:87345 ) 
# Shop.create(plaza:"MATAMOROS" , shop_number:284 , name:"ZAMASOR" , address:"AV. LAURO VILLAR # 1203 LOC 27,28,29" , suburb:"LAS ARBOLEDAS" , location:"MATAMOROS" , state_id: , cp:87448 ) 
# Shop.create(plaza:"MATAMOROS" , shop_number:285 , name:"ZAPATAERIA MATT" , address:"ABASOLO 7 Y 8 # 714" , suburb:"CENTRO" , location:"MATAMOROS" , state_id: , cp:87300 ) 
# Shop.create(plaza:"MATAMOROS" , shop_number:286 , name:"MATABAZA" , address:"ABASOLO 7 Y 8 # 709" , suburb:"CENTRO" , location:"MATAMOROS" , state_id: , cp:87300 ) 
# Shop.create(plaza:"MATAMOROS" , shop_number:287 , name:"ZAPAMATA" , address:"AV. PEDRO CARDENAS # 100 LOC 4,5 Y6" , suburb:"EJIDO 20 DE NOVIEMBRE" , location:"MATAMOROS" , state_id: , cp:87390 ) 
# Shop.create(plaza:"REYNOSA" , shop_number:289 , name:"ZAPATERIA REYNOSA" , address:"HIDALGO NTE # 559" , suburb:"CENTRO" , location:"REYNOSA" , state_id: , cp:88500 ) 
# Shop.create(plaza:"REYNOSA" , shop_number:290 , name:"ZAMAREY" , address:"HIDALGO NTE # 501" , suburb:"CENTRO" , location:"REYNOSA" , state_id: , cp:88500 ) 
# Shop.create(plaza:"REYNOSA" , shop_number:291 , name:"ZAPAREYSOR" , address:"CARRETERA MATAMOROS S/N LOC 14,15 Y 16B" , suburb:"ANTONIO J. BERMUDEZ" , location:"REYNOSA" , state_id: , cp:88727 ) 
# Shop.create(plaza:"REYNOSA" , shop_number:293 , name:"REYNOPEZA" , address:"CARR. REYNOSA/MONTERREY # 1000 PLAZA PERIFERICO 10-D" , suburb:"LOMAS DEL REAL JARACHINA SECC NTE" , location:"REYNOSA" , state_id: , cp:88730 ) 
# Shop.create(plaza:"MONTEMORELOS" , shop_number:294 , name:"MONTEMORELOZA" , address:"SIMON BOLIVA #1201 LOC 18,19 Y 20" , suburb:"MEXIQUITO" , location:"MONTEMORELOS" , state_id: , cp:67550 ) 
# Shop.create(plaza:"MONTERREY" , shop_number:292 , name:"MERCOREGIO" , address:"AV CENTRAL # 1403 LOC 5 Y 6" , suburb:"COLINAS DEL AEROPUERTO" , location:"PESQUERIA" , state_id: , cp:66655 ) 
# Shop.create(plaza:"MONTERREY" , shop_number:295 , name:"ZAPODACA" , address:"AV LA CONCORDIA # 800 LOCAL 5D Y 6D" , suburb:"LOS EBANOS" , location:"APOCADA" , state_id: , cp:66612 ) 
# Shop.create(plaza:"MONTERREY" , shop_number:296 , name:"MONTESOR" , address:"AVENIDA ABRAHAM LINCOLN # 4001 LOC C-18" , suburb:"PUERTA DE HIERRO" , location:"MONTERREY" , state_id: , cp:64348 ) 
# Shop.create(plaza:"MONTERREY" , shop_number:298 , name:"NOVOLEO" , address:"MORELOS OTE. # 210" , suburb:"CENTRO" , location:"MONTERREY" , state_id: , cp:64000 ) 
# Shop.create(plaza:"MONTERREY" , shop_number:299 , name:"MONTEMADEZA" , address:"CUAHUTEMOC NTE #933" , suburb:"CENTRO" , location:"MONTERREY" , state_id: , cp:64000 ) 
# Shop.create(plaza:"MONTERREY" , shop_number:300 , name:"MONTEFEZA" , address:"AV MIGUEL ALEMAN #789 LOC 14" , suburb:"CENTRO" , location:"APOCADA" , state_id: , cp:66600 ) 
# Shop.create(plaza:"MONTERREY" , shop_number:302 , name:"MONPAD" , address:"JUAREZ SUR # 574" , suburb:"CENTRO" , location:"MONTERREY" , state_id: , cp:64000 ) 
# Shop.create(plaza:"MONTERREY" , shop_number:304 , name:"ZAPATERIA NOEL NUEVO" , address:"JUAREZ SUR # 595" , suburb:"CENTRO" , location:"MONTERREY" , state_id: , cp:64000 ) 
# Shop.create(plaza:"MONTERREY" , shop_number:306 , name:"ZAPAREGIO" , address:"JUAREZ # 703" , suburb:"CENTRO" , location:"MONTERREY" , state_id: , cp:64000 ) 
# Shop.create(plaza:"MONTERREY" , shop_number:307 , name:"JUAREZ ZAMON" , address:"JUAREZ SUR # 520" , suburb:"CENTRO" , location:"MONTERREY" , state_id: , cp:64000 ) 
# Shop.create(plaza:"MONTERREY" , shop_number:308 , name:"MONJUAZA" , address:"JUAREZ SUR # 583" , suburb:"CENTRO" , location:"MONTERREY" , state_id: , cp:64000 ) 
# Shop.create(plaza:"MONTERREY" , shop_number:309 , name:"ZAMONARREOLA" , address:"JUAREZ SUR # 201" , suburb:"CENTRO" , location:"MONTERREY" , state_id: , cp:64000 ) 
# Shop.create(plaza:"LAREDO" , shop_number:311 , name:"ZAPATERIA NUELATA" , address:"GUERRERO NTE # 1113" , suburb:"CENTRO" , location:"NUEVO LAREDO" , state_id: , cp:88000 ) 
# Shop.create(plaza:"LAREDO" , shop_number:312 , name:"LAREQUEZA" , address:"GUERRERO NTE # 1001" , suburb:"CENTRO" , location:"NUEVO LAREDO" , state_id: , cp:88000 ) 
# Shop.create(plaza:"SALTILLO" , shop_number:313 , name:"SALTISOR" , address:"CRT. A LOS GONZALEZ # 365 LOC D-8" , suburb:"OCEANIA" , location:"SALTILLO" , state_id: , cp:25290 ) 
# Shop.create(plaza:"SALTILLO" , shop_number:314 , name:"SALTIZAPA" , address:"PADRE FLORES # 317" , suburb:"CENTRO" , location:"SALTILLO" , state_id: , cp:25000 ) 
# Shop.create(plaza:"SALTILLO" , shop_number:315 , name:"ZAPASALCO" , address:"ALDAMA # 387" , suburb:"CENTRO" , location:"SALTILLO" , state_id: , cp:25000 ) 
# Shop.create(plaza:"SALTILLO" , shop_number:316 , name:"SALTILLOZA" , address:"ALDAMA # 404" , suburb:"CENTRO" , location:"SALTILLO" , state_id: , cp:25000 ) 
# Shop.create(plaza:"SALTILLO" , shop_number:317 , name:"ZAPAMIRASIERRA" , address:"BLVD FUNDADORES # 7690 LOC 15,16,17 Y 18" , suburb:"MIRASIERRA" , location:"SALTILLO" , state_id: , cp:25016 ) 
# Shop.create(plaza:"SALTILLO" , shop_number:319 , name:"SENDESALTI" , address:"BLVD ANTONIO CARDENAS # 4159 LOC D7 Y D8" , suburb:"PARQUES DE LA CAÑADA" , location:"SALTILLO" , state_id: , cp:25090 ) 
# Shop.create(plaza:"PIEDRAS NEGRAS" , shop_number:318 , name:"PIEDRAZA" , address:"ZARAGOZA # 301 NTE" , suburb:"CENTRO" , location:"PIEDRAS NEGRAS" , state_id: , cp:26000 ) 
# Shop.create(plaza:"CD. ACUÑA" , shop_number:320 , name:"ZAPACUÑA" , address:"GUERRERO # 200 SUR" , suburb:"CENTRO" , location:"CD. ACUÑA" , state_id: , cp:26200 ) 
# Shop.create(plaza:"CD. ACUÑA" , shop_number:321 , name:"CUÑAZAPA" , address:"LIB. EMILIO MENDOZA CISNEROS # 2000 INT C-2" , suburb:"AEROPUERTO" , location:"CD. ACUÑA" , state_id: , cp:26230 ) 
# Shop.create(plaza:"CD. ACUÑA" , shop_number:322 , name:"MERCOZAPA" , address:"GUERRERO # 2000" , suburb:"VISTAHERMOSA" , location:"CD. ACUÑA" , state_id: , cp:26290 ) 
# Shop.create(plaza:"MONCLOVA" , shop_number:335 , name:"ZAPAMONCLOVA" , address:"HIDALGO # 310 SUR" , suburb:"CENTRO" , location:"MONCLOVA" , state_id: , cp:25700 ) 
# Shop.create(plaza:"MONCLOVA" , shop_number:336 , name:"MONCLOVA ZAPATERA" , address:"HIDALGO # 110 SUR" , suburb:"CENTRO" , location:"MONCLOVA" , state_id: , cp:25700 ) 
# Shop.create(plaza:"LEON" , shop_number:1 , name:"ZAPAFIERA SA DE CV" , address:"5 DE MAYO 156 AL 160" , suburb:"CENTRO" , location:"LEON" , state_id: , cp:37000 ) 
# Shop.create(plaza:"LEON" , shop_number:2 , name:"BELISARIO ZAPATERA SA DE CV" , address:"JUSTO SIERRA 136" , suburb:"CENTRO" , location:"LEON" , state_id: , cp:37000 ) 
# Shop.create(plaza:"LEON" , shop_number:3 , name:"CALZADO ARMARIO SA DE CV" , address:"MADERO 102 Y 104" , suburb:"CENTRO" , location:"LEON" , state_id: , cp:37000 ) 
# Shop.create(plaza:"LEON" , shop_number:5 , name:"ZAPATERA PADHNOS SA DE CV" , address:"5 DE MAYO 101" , suburb:"CENTRO" , location:"LEON" , state_id: , cp:37000 ) 
# Shop.create(plaza:"LEON" , shop_number:7 , name:"CENTRALEZA SA DE CV" , address:"HILARIO MEDINA 501" , suburb:"KILLIAN" , location:"LEON" , state_id: , cp:37260 ) 
# Shop.create(plaza:"LEON" , shop_number:8 , name:"ZAPALESER SA DE CV" , address:"AQUILES SERDAN 102" , suburb:"CENTRO" , location:"LEON" , state_id: , cp:37000 ) 
# Shop.create(plaza:"LEON" , shop_number:9 , name:"MAYORZAPA SA DE CV" , address:"AV LAS TORRES 2002 LOC 10 Y 11" , suburb:"VALLE DEL CAMPESTRE" , location:"LEON" , state_id: , cp:37150 ) 
# Shop.create(plaza:"QUERETARO" , shop_number:11 , name:"ZAPAMER S.A. DE C.V." , address:"S/N PLAZA DE LAS AMERICAS" , suburb:"CARRETAS" , location:"QUERETARO" , state_id: , cp:76050 ) 
# Shop.create(plaza:"QUERETARO" , shop_number:12 , name:"ZAPALLEQRO S.A. DE C.V." , address:"16 DE SEPTIEMBRE #77 PTE." , suburb:"CENTRO" , location:"QUERETARO" , state_id: , cp:76000 ) 
# Shop.create(plaza:"QUERETARO" , shop_number:14 , name:"QUERETAZA S.A. DE C.V." , address:"ZARAGOZA OTE. #27" , suburb:"CENTRO" , location:"QUERETARO" , state_id: , cp:76000 ) 
# Shop.create(plaza:"QUERETARO" , shop_number:15 , name:"QUEREZAPA S.A. DE C.V." , address:"ALLENDE #49 - A" , suburb:"CENTRO" , location:"QUERETARO" , state_id: , cp:76000 ) 
# Shop.create(plaza:"QUERETARO" , shop_number:18 , name:"SORIAQUER S.A. DE C.V." , address:"MADERO #19 PTE." , suburb:"CENTRO" , location:"QUERETARO" , state_id: , cp:76000 ) 
# Shop.create(plaza:"CELAYA " , shop_number:16 , name:"ZAPACELA S.A. DE C.V." , address:"MORELOS #111" , suburb:"CENTRO" , location:"CELAYA" , state_id: , cp:38000 ) 
# Shop.create(plaza:"CELAYA " , shop_number:17 , name:"ZAPATERA AYALEC SA DE CV" , address:"PORTAL GUADALUPE #106" , suburb:"CENTRO" , location:"CELAYA " , state_id: , cp:38000 ) 
# Shop.create(plaza:"IRAPUATO " , shop_number:19 , name:"ZAPATERA SANDEGO S.A DE C.V" , address:"SANTOS DEGOLLADO 96" , suburb:"ZONA CENTRO" , location:"IRAPUATO" , state_id: , cp:36500 ) 
# Shop.create(plaza:"IRAPUATO " , shop_number:22 , name:"IRASANDE S.A DE C,V" , address:"SANTOS DEGOLLADO 202 Y 212" , suburb:"ZONA CENTRO" , location:"IRAPUATO" , state_id: , cp:36500 ) 
# Shop.create(plaza:"IRAPUATO " , shop_number:21 , name:"IRAZAPA S.A DE C.V" , address:"REVOLUCION ESQ. BLVD. D. ORDAZ" , suburb:"ZONA CENTRO" , location:"IRAPUATO" , state_id: , cp:36500 ) 
# Shop.create(plaza:"SAN JUAN DEL RIO" , shop_number:23 , name:"ZAJUARIO S.A DE C.V" , address:"AV. HIDALGO #35" , suburb:"CENTRO" , location:"SAN JUAN DEL RIO " , state_id: , cp:76800 ) 
# Shop.create(plaza:"SALAMANCA" , shop_number:25 , name:"ZAPATERA,SALGO" , address:"JUAREZ.124" , suburb:"CENTRO" , location:"SALAMANCA" , state_id: , cp:36700 ) 
# Shop.create(plaza:"GUANAJUATO" , shop_number:27 , name:"GUANAZAPA S.A. DE C.V." , address:"JUAREZ #252 Y #254" , suburb:"CENTRO" , location:"GUANAJUATO" , state_id: , cp:36000 ) 
# Shop.create(plaza:"ECATEPEC" , shop_number:78 , name:"ECATEZAPA S.A DE C.V" , address:"CARRETERA MEXICO TEPEXPAN #8 LOCAL 5D Y 6D" , suburb:"PLAZA GRAN PATIO" , location:"ECATEPEC" , state_id: , cp:55064 ) 
# Shop.create(plaza:"CIUDAD DE MEXICO" , shop_number:80 , name:"ZAPAZCA S.A. DE C.V." , address:"ESPERANZA #22-F" , suburb:"AZCAPOTZALCO" , location:"CIUDAD DE MÉXICO" , state_id: , cp:02000 ) 
# Shop.create(plaza:"CUAUTITLAN" , shop_number:83 , name:"CUAUTIZAPA S.A. DE C.V." , address:"AV.HIDALGO #6" , suburb:"CENTRO" , location:"CUAUTITLAN" , state_id: , cp:54800 ) 
# Shop.create(plaza:"TLALNEPANTLA" , shop_number:84 , name:"ZAPATLAL S.A DE C.V" , address:"PORFIRIO DIAZ N-24" , suburb:"CENTRO" , location:"TLALNEPANTLA" , state_id: , cp:54000 ) 
# Shop.create(plaza:"CIUDAD DE MEXICO" , shop_number:86 , name:"ZAPAGANTE S.A DE C.V" , address:"GANTE #12 LOC I" , suburb:"CENTRO" , location:"CDMX" , state_id: , cp:6000 ) 
# Shop.create(plaza:"NAUCALPAN" , shop_number:87 , name:"NUACALZA S.A DE C.V" , address:"AV. VIA GUSTAVO BAZ N.3-A" , suburb:"SAN BARTOLO CENTRO" , location:"NUACALPAN" , state_id: , cp:53000 ) 
# Shop.create(plaza:"IXTAPALUCA" , shop_number:88 , name:"IZTAPALUZA S.A. DE C.V." , address:"CARR. FED. MEX-CUAUTLA #1 BLOQUE D LOC.8 Y9" , suburb:"SANTA BARBARA" , location:"ESTADO DE MEXICO" , state_id: , cp:56538 ) 
# Shop.create(plaza:"PACHUCA" , shop_number:89 , name:"ZAPACHU SA DE CV" , address:"DORIA 105" , suburb:"CENTRO" , location:"PACHUCA " , state_id: , cp:42000 ) 
# Shop.create(plaza:"PACHUCA" , shop_number:90 , name:"PACHUZAPA SA DE CV" , address:"GENARO GUZMAN MAYER 101" , suburb:"CENTRO" , location:"PACHUCA " , state_id: , cp:42000 ) 
# Shop.create(plaza:"TULANCINGO" , shop_number:93 , name:"TULANZAPA S.A. DE C.V." , address:"AV. 21 DE MARZO # 201-C" , suburb:"CENTRO" , location:"TULANCINGO" , state_id: , cp:43600 ) 
# Shop.create(plaza:"TULA DE ALLENDE" , shop_number:94 , name:"TULA ZAPATERA S.A. DE C.V." , address:"AV PROL ZARAGOZA 110" , suburb:"CENTRO" , location:"TULA DE ALLENDE" , state_id: , cp:42800 ) 
# Shop.create(plaza:"TOLUCA" , shop_number:96 , name:"TOLUSOR SA DE CV" , address:"BOULEVAR MIGUEL ALEMAN VALDE 55 LOC. 7 Y 8 D" , suburb:"CORREDOR INDUSTRIAL" , location:"TOLUCA LERMA" , state_id: , cp:52004 ) 
# Shop.create(plaza:"TOLUCA" , shop_number:97 , name:"TOLU SA DE CV" , address:"INDEPENDENCIA PTE. N. 102 INT. A" , suburb:"CENTRO" , location:"TOLUCA" , state_id: , cp:50000 ) 
# Shop.create(plaza:"TOLUCA" , shop_number:98 , name:"ZAJUATO SA DE CV" , address:"AV. BENITO JUAREZ SUR N. 120-A" , suburb:"CENTRO" , location:"TOLUCA" , state_id: , cp:50000 ) 
# Shop.create(plaza:"TOLUCA" , shop_number:99 , name:"ZARAYTO SA DE CV" , address:"IGNACIO RAYON NTE. N. 508" , suburb:"CENTRO" , location:"TOLUCA" , state_id: , cp:50000 ) 
# Shop.create(plaza:"OAXACA" , shop_number:100 , name:"OAXAZAPA S.A DE C.V" , address:"MIGUEL CABRERA Nº 122" , suburb:"CENTRO" , location:"OAXACA DE JUAREZ" , state_id: , cp:68000 ) 
# Shop.create(plaza:"OAXACA" , shop_number:101 , name:"ZAPAOAXACA S. A DE C.V" , address:"BUSTAMANTE Nº 115" , suburb:"CENTRO" , location:"OAXACA DE JUAREZ" , state_id: , cp:68000 ) 
# Shop.create(plaza:"OAXACA" , shop_number:102 , name:"OAXACA ZAPATERA S.A DE C.V" , address:"LAS CASAS Nº 104" , suburb:"CENTRO" , location:"OAXACA DE JUAREZ" , state_id: , cp:68000 ) 
# Shop.create(plaza:"OAXACA" , shop_number:107 , name:"ZAOAXA S.A DE C.V" , address:"LAS CASAS Nº 814" , suburb:"CENTRO" , location:"OAXACA DE JUAREZ" , state_id: , cp:68000 ) 
# Shop.create(plaza:"CUERNAVACA " , shop_number:104 , name:"ZAPATERIA GUERCU SA DE CV" , address:"GUERRERO # 8" , suburb:"CENTRO" , location:"CUERNAVACA" , state_id: , cp:62000 ) 
# Shop.create(plaza:"CUERNAVACA " , shop_number:105 , name:"ZAMACUE SA DE CV" , address:"MATAMOROS # 14 " , suburb:"CENTRO" , location:"CUERNAVACA" , state_id: , cp:62000 ) 
# Shop.create(plaza:"CUERNAVACA " , shop_number:106 , name:"CUERNAZAPA SA DE CV" , address:"GUERRERO # 28" , suburb:"CENTRO" , location:"CUERNAVACA" , state_id: , cp:62000 ) 
# Shop.create(plaza:"CUAUTLA" , shop_number:108 , name:"CUAUTLAZAPA S.A. DE C.V" , address:"LOS BRAVO ESQ ING RAMIREZ #2" , suburb:"CENTRO" , location:"CUAUTLA MORELOS" , state_id: , cp:62740 ) 
# Shop.create(plaza:"ZITACUARO" , shop_number:110 , name:"ZITAZAPA SA DE CV" , address:"HIDALGO PTE. #8" , suburb:"CENTRO" , location:"ZITACUARO" , state_id: , cp:61500 ) 
# Shop.create(plaza:"TENANCINGO " , shop_number:111 , name:"TENANCINGO ZAPATERA SA DE CV" , address:"FRANCISCO I MADERO #314" , suburb:"CENTRO" , location:"TENANCINGO" , state_id: , cp:52400 ) 
# Shop.create(plaza:"TENANGO" , shop_number:112 , name:"TENANGO ZAPATERA S.A. DE C.V." , address:"MIGUEL HIDALGO Y COSTILLA OTE. No. 110" , suburb:"CENTRO" , location:"TENANGO DEL VALLE" , state_id: , cp:52300 ) 
# Shop.create(plaza:"PUEBLA" , shop_number:113 , name:"DIEZ PONIENTE SA DE CV" , address:"10 PTE 107" , suburb:"CENTRO" , location:"PUEBLA" , state_id: , cp:72000 ) 
# Shop.create(plaza:"PUEBLA" , shop_number:116 , name:"TRES NORTE SA DE CV" , address:"3 NTE 607" , suburb:"CENTRO" , location:"PUEBLA" , state_id: , cp:72000 ) 
# Shop.create(plaza:"PUEBLA" , shop_number:117 , name:"PUEBLA ZAPTERA SA DE CV" , address:"3 NTE 210" , suburb:"CENTRO" , location:"PUEBLA" , state_id: , cp:72000 ) 
# Shop.create(plaza:"PUEBLA" , shop_number:119 , name:"OCHO Y CINCO ZAPATERA SA DE CV" , address:"8 PONIENTE 501" , suburb:"CENTRO" , location:"PUEBLA" , state_id: , cp:72000 ) 
# Shop.create(plaza:"PUEBLA" , shop_number:120 , name:"PUMAZA SA DE CV" , address:"5 DE MAYO 408" , suburb:"CENTRO" , location:"PUEBLA" , state_id: , cp:72000 ) 
# Shop.create(plaza:"PUEBLA" , shop_number:122 , name:"PUZAMA SA DE CV" , address:"5 DE MAYO 602" , suburb:"CENTRO" , location:"PUEBLA" , state_id: , cp:72000 ) 
# Shop.create(plaza:"CHIAUHTEMPAN" , shop_number:124 , name:"CHIAUTEMZA SA DE CV" , address:"IGNACIO PICAZO NORTE 14-A" , suburb:"CENTRO" , location:"CHIATEMPAN" , state_id: , cp:90800 ) 
# Shop.create(plaza:"APIZACO" , shop_number:125 , name:"ZAPIZACO S.A.DEC.V." , address:"AQUILES SERDAN 102-A" , suburb:"CENTRO" , location:"APIZACO" , state_id: , cp:90300 ) 
# Shop.create(plaza:" CHOLULA" , shop_number:126 , name:"CHOLUZAPA S.A.DE C.V." , address:"HIDALGO NO. 113" , suburb:"CENTRO" , location:"SAN PEDRO CHOLULA " , state_id: , cp:72760 ) 
# Shop.create(plaza:"TEHUACAN" , shop_number:127 , name:"ZAPATEHUA SA DE CV" , address:"INDEPENDENCIA ORIENTE 100" , suburb:"CENTRO" , location:"TEHUACAN" , state_id: , cp:75700 ) 
# Shop.create(plaza:"TEHUACAN" , shop_number:128 , name:"TEHUAZA SA DE CV" , address:"TERCERA DE AGUSTIN A CACHO 333" , suburb:"CENTRO" , location:"TEHUACAN" , state_id: , cp:75700 ) 
# Shop.create(plaza:"SAN MARTIN" , shop_number:129 , name:"ZAPAMARTIN S. A. DE C. V." , address:"HIDALGO OTE. N.4" , suburb:"CENTRO" , location:"SAN MARTIN TEX." , state_id: , cp:74000 ) 
# Shop.create(plaza:"SAN MARTIN" , shop_number:132 , name:"SANMARTINZA S.A. DE C.V." , address:"5 DE MAYO SUR N. 201" , suburb:"CENTRO" , location:"SAN MARTIN TEX." , state_id: , cp:74000 ) 
# Shop.create(plaza:"ATLIXCO" , shop_number:130 , name:"ZAPATLIXCO SA DE CV" , address:"AV. INDEPENDENCIA #107" , suburb:"CENTRO" , location:"ATLIXCO" , state_id: , cp:74200 ) 
# Shop.create(plaza:"TLAXCALA" , shop_number:134 , name:"TLAXCALZAPA S.A DE C.V" , address:"PROLONGACION 20 DE NOV. #5" , suburb:"CENTRO" , location:"TLAXCALA" , state_id: , cp:90000 ) 
# Shop.create(plaza:"IZUCAR" , shop_number:135 , name:"IZUCARZAPA S.A DE C.V" , address:"BENITO JUAREZ NO.6" , suburb:"CENTRO" , location:"IZUCAR DE MATAMOROS" , state_id: , cp:74400 ) 
# Shop.create(plaza:"TECAMACHALCO" , shop_number:136 , name:"TECAMACALZA SA DE CV" , address:"2 SUR 307" , suburb:"CENTRO" , location:"TECAMACHALCO" , state_id: , cp:75480 ) 
# Shop.create(plaza:"ACAPULCO" , shop_number:137 , name:"ZACAPUL SA DE CV" , address:"JUAN RAMON ESCUDERO #15" , suburb:"CENTRO" , location:"ACAPULCO DE JUAREZ" , state_id: , cp:39300 ) 
# Shop.create(plaza:"ACAPULCO" , shop_number:138 , name:"ZABELACA SA DE CV" , address:"CUAUHTEMOC #419" , suburb:"CENTRO" , location:"ACAPULCO DE JUAREZ" , state_id: , cp:39300 ) 
# Shop.create(plaza:"ACAPULCO" , shop_number:139 , name:"ZAMINACA SA DE CV" , address:"MELCHOR OCAMPO #1" , suburb:"CENTRO" , location:"ACAPULCO DE JUAREZ" , state_id: , cp:39300 ) 
# Shop.create(plaza:"ACAPULCO" , shop_number:140 , name:"ZAPACONACA SA DE CV" , address:"CONSTITUYENTES #529" , suburb:"CENTRO" , location:"ACAPULCO DE JUAREZ" , state_id: , cp:39300 ) 
# Shop.create(plaza:"PUERTO ESCONDIDO" , shop_number:141 , name:"ESCONDIZAPA S.A DE C.V" , address:"AV. OAXACA #2547" , suburb:"SECTOR REFORMA" , location:"PUERTO ESCONDIDO" , state_id: , cp:71983 ) 
# Shop.create(plaza:"IGUALA" , shop_number:142 , name:"ZAPAIGUALA SA DE CV" , address:"MORELOS # 4" , suburb:"CENTRO" , location:"IGUALA DE LA INDEPENDENCIA" , state_id: , cp:40000 ) 
# Shop.create(plaza:"CHILPANCINGO" , shop_number:143 , name:"CHILZAPA SA DE CV" , address:"AV. JUAN RIUZ DE ALARCON #3-A" , suburb:"CENTRO" , location:"CHILPANCINGO" , state_id: , cp:39000 ) 
# Shop.create(plaza:"CHILPANCINGO" , shop_number:144 , name:"ZAPACHILPAN SA DE CV" , address:"AV. GUERRERO #31-A" , suburb:"CENTRO" , location:"CHILPANCINGO" , state_id: , cp:39000 ) 
# Shop.create(plaza:"CHILPANCINGO" , shop_number:145 , name:"CHILPANZAPA SA DE CV" , address:"AV. INSURGENTES #17" , suburb:"BENITO JUAREZ" , location:"CHILPANCINGO" , state_id: , cp:39017 ) 
# Shop.create(plaza:"OMETEPEC" , shop_number:147 , name:"OMETEZAPA S.A. DE C.V." , address:"AV. CUAUTEMOC NUM. 31" , suburb:"CENTRO" , location:"OMETEPEC" , state_id: , cp:41706 ) 
# Shop.create(plaza:"JOJUTLA" , shop_number:150 , name:"JOJUTLAZA SA DE CV" , address:"ALTAMIRANO 106-D" , suburb:"CENTRO" , location:"JOJUTLA" , state_id: , cp:72900 ) 
# Shop.create(plaza:"PINOTEPA NAL OAXACA" , shop_number:151 , name:"PINOTEZAPA S.A DE C.V" , address:"BENITO JUAREZ #208" , suburb:"CENTRO" , location:"PINOTEPA NAL." , state_id: , cp:71600 ) 
# Shop.create(plaza:"CINTALAPA" , shop_number:152 , name:"CINTALAZAPA S.A DE C.V" , address:"1ª PONIENTE NORTE #58" , suburb:"CENTRO" , location:"CINTALAPA DE FIGUIEROA" , state_id: , cp:30400 ) 
# Shop.create(plaza:"TUXTLA" , shop_number:153 , name:"QUINZATUX, S.A. DE C.V." , address:"5a. AVENIDA SUR N° 112 ESQUINA CALLE CENTRAL" , suburb:"ZONA CENTRO" , location:"TUXTLA GUTIERREZ" , state_id: , cp:29000 ) 
# Shop.create(plaza:"TUXTLA" , shop_number:154 , name:"TUXTLAZAPA, S.A. DE C.V." , address:"CALLE CENTRAL SUR N° 452" , suburb:"ZONA CENTRO" , location:"TUXTLA GUTIERREZ" , state_id: , cp:29000 ) 
# Shop.create(plaza:"TUXTLA" , shop_number:155 , name:"TUGUZA, S.A. DE C.V." , address:"1a. PONIENTE ESQUINA 3a. SUR N° 377" , suburb:"ZONA CENTRO" , location:"TUXTLA GUTIERREZ" , state_id: , cp:29000 ) 
# Shop.create(plaza:"TUXTLA" , shop_number:156 , name:"ZACHITUX, S.A. DE C.V." , address:"AVENIDA CENTRAL ESQUINA 6a. PONIENTE S/N°" , suburb:"ZONA CENTRO" , location:"TUXTLA GUTIERREZ" , state_id: , cp:29000 ) 
# Shop.create(plaza:"TUXTLA" , shop_number:157 , name:"ZAPATUX, S.A. DE C.V." , address:"1a. PONIENTE N° 617 ESQUINA 5a. AVENIDA SUR" , suburb:"ZONA CENTRO" , location:"TUXTLA GUTIERREZ" , state_id: , cp:29000 ) 
# Shop.create(plaza:"TAPACHULA" , shop_number:158 , name:"ZAPATACHI S.A.DE C.V." , address:"3RA.CALLE PONIENTE NO.29" , suburb:"CENTRO" , location:"TAPACHULA" , state_id: , cp:30700 ) 
# Shop.create(plaza:"TAPACHULA" , shop_number:159 , name:"TAPASEXTA S.A. DE C.V." , address:"6A.AVENIDA NORTE NO.27" , suburb:"CENTRO" , location:"TAPACHULA" , state_id: , cp:30700 ) 
# Shop.create(plaza:"TAPACHULA" , shop_number:160 , name:"TAPAZAPA S.A.DE C.V." , address:"10A.AVE.NORTE NO.29" , suburb:"CENTRO" , location:"TAPACHULA" , state_id: , cp:30700 ) 
# Shop.create(plaza:"HUIXTLA" , shop_number:161 , name:"ZAPAHUIXTLA S.A DE C.V" , address:"AV. CENTRAL NTE. ESQ.ZARAGOZA" , suburb:"BARRIO EL" , location:"HUIXTLA" , state_id: , cp:30640 ) 
# Shop.create(plaza:"COMITAN" , shop_number:162 , name:"COMITANZAPA SA DE CV" , address:"1ERA AVE OTE SUR NUM 13" , suburb:"CENTRO" , location:"COMITAN" , state_id: , cp:30000 ) 
# Shop.create(plaza:"OCOSINGO" , shop_number:163 , name:"OCOZAPA SA DE CV" , address:"2a Av.sur oriente # 20" , suburb:"centro " , location:"ocosingo,chiapas" , state_id: , cp:29950 ) 
# Shop.create(plaza:"SAN CRISTOBAL" , shop_number:164 , name:"ZACRICA, S.A. DE C.V" , address:"AV GENERAL UTRILLA No. 57" , suburb:"CENTRO" , location:"SAN CRISTOBAL DE LAS CASAS" , state_id: , cp:29200 ) 
# Shop.create(plaza:"SAN CRISTOBAL" , shop_number:165 , name:"CRISTOBALZA, S.A. DE C.V" , address:"AV GENERAL UTRILLA No.67-B" , suburb:"CENTRO" , location:"SAN CRISTOBAL DE LAS CASAS" , state_id: , cp:29200 ) 
# Shop.create(plaza:"TONALA" , shop_number:166 , name:"TONACHIAPAS S.A. DE C.V." , address:"AV. HIDALGO NUM. 133" , suburb:"BARRIO NICATAN" , location:"TONALA" , state_id: , cp:30500 ) 
# Shop.create(plaza:"PIJIJIAPAN" , shop_number:167 , name:"PIJIZAPA SA DE CV" , address:"central norte #312 esq 2a ave norte" , suburb:"centro" , location:"pijijiapan,chiapas" , state_id: , cp:30540 ) 
